title: PORTFOLIO
default_lang: en
author:
  name: 'Ucha Chilahava '
  email: ucha19871@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Ucha Chilahava Profile'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
