enabled: true
site_title:
  enabled: true
google_fonts_logo:
  enabled: true
fontawesome:
  enabled: true
google_prettify:
  enabled: true
dropdown:
  enabled: false
mobilemenu_breakpoint: large
mobilemenu_position: left
foundation_offcanvas_js:
  enabled: true
foundation_util_mediaQuery_js:
  enabled: true
foundation_util_motion_js:
  enabled: true
foundation_util_touch_js:
  enabled: true
foundation_util_triggers_js:
  enabled: true
css_bones:
  enabled: true
css_global_styles:
  enabled: true
css_grid:
  enabled: true
css_flex_grid:
  enabled: false
css_typography:
  enabled: true
css_button:
  enabled: true
css_forms:
  enabled: true
css_visibility_classes:
  enabled: true
css_float_classes:
  enabled: true
css_menu:
  enabled: true
css_off_canvas:
  enabled: true
css_pagination:
  enabled: true
css_sticky:
  enabled: true
css_table:
  enabled: true
animate_css:
  enabled: true
wow_js:
  enabled: true
foundation_abide_js:
  enabled: true
foundation_accordion_js:
  enabled: true
foundation_accordionMenu_js:
  enabled: true
foundation_drilldown_js:
  enabled: true
foundation_dropdown_js:
  enabled: true
foundation_dropdownMenu_js:
  enabled: true
foundation_equalizer_js:
  enabled: true
foundation_interchange_js:
  enabled: true
foundation_magellan_js:
  enabled: true
foundation_orbit_js:
  enabled: true
foundation_responsiveMenu_js:
  enabled: true
foundation_responsiveToggle_js:
  enabled: true
foundation_reveal_js:
  enabled: true
foundation_slider_js:
  enabled: true
foundation_sticky_js:
  enabled: true
foundation_tabs_js:
  enabled: true
foundation_toggler_js:
  enabled: true
foundation_tooltip_js:
  enabled: true
foundation_util_box_js:
  enabled: false
foundation_util_keyboard_js:
  enabled: false
foundation_util_nest_js:
  enabled: false
foundation_util_timerAndImageLoader_js:
  enabled: false
css_custom:
  enabled: false
css_accordion:
  enabled: false
css_accordion_menu:
  enabled: false
css_badge:
  enabled: false
css_breadcrumbs:
  enabled: false
css_button_group:
  enabled: false
css_callout:
  enabled: true
css_close_button:
  enabled: false
css_drilldown_menu:
  enabled: false
css_dropdown:
  enabled: false
css_dropdown_menu:
  enabled: false
css_flex_video:
  enabled: false
css_label:
  enabled: false
css_media_object:
  enabled: false
css_orbit:
  enabled: false
css_progress_bar:
  enabled: false
css_slider:
  enabled: false
css_reveal:
  enabled: false
css_switch:
  enabled: false
css_tabs:
  enabled: false
css_thumbnail:
  enabled: false
css_title_bar:
  enabled: false
css_tooltip:
  enabled: false
css_top_bar:
  enabled: false
css_ui_transitions:
  enabled: false
css_ui_animations:
  enabled: false
